name             'yum-cron'
maintainer       'Oregon State University'
maintainer_email 'chef@osuosl.org'
license          'Apache 2.0'
description      'Installs/Configures yum-cron'
long_description 'Installs/Configures yum-cron'
version          '0.1.1'

supports         'centos', '~> 6.0'
supports         'centos', '~> 7.0'
